- README.md
- contracts/LifToken.sol
- contracts/zeppelin/Ownable.sol
- contracts/zeppelin/SafeMath.sol
- contracts/zeppelin/token/CrowdsaleToken.sol
- package.json
- test/LifToken.js
Added ownership, fees gathered on every transfer with value, setPrice and setFee methods added, using correct decimals, better and more test cases checking every field of the contract.
The token contract now will have an owner, can be one person or an entire organization, it will gain money in tokens charging 1% fee per transaction with value.
+ Test cases, checking that the main values are the correct on every test.
> Added ownership, fees, setPrice(), setFee and correct decimals.

- README.md
- contracts/LifToken.sol
- contracts/test-helpers/Message.sol
- test/LifToken.js
Added call execution on transferData calls, not allowing transfers and approvals to token contract. Fix #14
> Added call execution on transfers, and fix bug ot send to token.

- README.md
- contracts/LifToken.sol
- test/Crowdsale.js
- test/DAO.js
- test/LifToken.js
- test/helpers.js
Contract code review with some changes, removed onlyTokenHolders modifier, added the possibility to owners to withdraw ethers from contract and few more changes. Changes on tests to match the changes on contract.
Added another section of important variables on readme.
> Contract code refactor, important variables section added on readme

- contracts/LifToken.sol
- package.json
- test/LifToken.js
- test/helpers.js
Fix #30 Fix #29 
Using zeppelin-solidity 1.0.4 version because next version use safeMath as lib and break our tests.
> Added approveData, using abiDecoder and fix zeppelin version.

- test/helpers.js
Usage: `WT_DEBUG=true npm test`
> Allow to set DEBUG_MODE via WT_DEBUG env var

- README.md
- scripts/test.sh
Example:
npm test -- test/Crowdsale.js
> test script: Allow to run a specific test file

- test/helpers.js
Makes the test code more readable and easier to change
> Refactor: use specific vars via let in test instead of values array

- test/Crowdsale.js
- test/helpers.js
> Remove from:accounts[0] in calls to distributeTokens

- contracts/FuturePayment.sol
- contracts/LifCrowdsale.sol
- contracts/LifToken.sol
- migrations/2_deploy_contracts.js
- package.json
- test/Crowdsale.js
- test/DAO.js
- test/LifToken.js
- test/helpers.js
> Extract LifCrowdsale contract

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
Reduces the quantity of blocks to wait for in Crowdsale tests, making the tests to run faster
> Reduce waiting for blocks in Crowdsale tests

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
A few minor refactors in tests and contracts.
> Some refactor

- test/helpers.js
Logs only every 5 blocks. Refactors one to call the other
> Tweaks in wait for blocks helpers

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/helpers.js
> Modify presale payments policy from discount to bonus rate

- contracts/LifToken.sol
More info: https://blog.coinfabrik.com/smart-contract-short-address-attack-mitigation-failure/
Fixes #57
> Remove short address checks: not effective and bring new problems

- contracts/FuturePayment.sol
- contracts/LifCrowdsale.sol
- contracts/LifDAOInterface.sol
- contracts/LifInterface.sol
- contracts/LifToken.sol
Created contract interfaces, this help us and future developers to use the Lif contracts with only requesting the interface of the contracts, and also help us to use the interface between the crowdsale and future payments contracts.
> Adding contract interfaces

- truffle.js
We'll add it later, but for now it just it's trouble when trying
to run tests and network is offline
> Remove ropsten from truffle.js from now

- contracts/FuturePayment.sol
- contracts/LifCrowdsale.sol
- contracts/LifToken.sol
> Replace throw with require/assert

- contracts/LifInterface.sol
- contracts/LifToken.sol
> Removed unnecesary doCall parameter in functions

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/helpers.js
Also makes setStatus to throw when not from owner or from self
> Refactor prop based test commands to allow for better error handling

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/helpers.js
Also requires to be after startBlock to run a successful addPresalePayment tx
Ref: #65
> Add addPresalePayment command to prop based test

- test/CrowdsaleGenTest.js
Checks lastPrice, tokensSold and totalPresaleWei
Ref: #65
> Add some state checks at the end of prop based test

- contracts/LifToken.sol
Can help in debugging but also might have other use cases in the future
> Add TokensIssued event

- test/CrowdsaleGenTest.js
- test/helpers.js
Wait block was waiting for one extra block because when it got down to zero
it still waited one more block until block count was negative
> Test helpers: Wait block should not wait for an extra block

- test/helpers.js
- test/helpers/advanceToBlock.js
Uses implementation from zeppelin-solidity now
Fixes #76
> Fix waitToBlock: it was not consistently waiting for the block to be mined

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
> Fix weiRaised amount based on last price (which follows a decreasing trend b/c it's a reverse dutch auction)

- contracts/LifCrowdsale.sol
- test/CrowdsaleGenTest.js
Added finalize crowdsale command and crowdsaleEnded variable in state.
> Finalize crowdsale command

- test/CrowdsaleGenTest.js
> Add pause token command

- contracts/LifMarketMaker.sol
- package.json
- test/MarketMaker.js
- truffle.js
- yarn.lock
Let's take the draft test scenario we wrote all together and make it work doing real calls to `sendTokens`, `getTokens`, `claimEth` and all the expected assertions
/cc @kvbik @AugustoL
> Make market maker test to work

- contracts/LifMarketMaker.sol
- test/MarketMaker.js
Foundation can now claim all the remaining eth at the end of the Market Maker
> Market Maker finalization: claim remaining eth

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/LifToken.js
- test/MarketMaker.js
- test/helpers.js
After the crowdsale ends if it succeed and raise more than 10M usd it iss going to create a market maker contract, the amount of periods of the market maker depends on the balance that it is going to receive, if it is less than 40M usd it will have 24 periods, if not 48.
To calculate the crowdsale caps and balance to be sent to the market maker with more precision,  the caps are set in USD dollars on the crowdsale contract and a function to set how much is the wei/USD before public presale and ICO has been added.
> Integrate Market Maker in Crowdsale

- contracts/LifCrowdsale.sol
It was still passing the old spread argument which was removed recently
> Fix the MarketMaker create call in Crowdsale

- test/CrowdsaleGenTest.js
> Fixes sendTransaction command in gen test and adds 2 specific examples that were failing

- test/CrowdsaleGenTest.js
> Adding claimEth command to crowdsale gen test

- contracts/LifToken.sol
- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
> Add pausable logic to transfer, approve and transferFrom

- test/CrowdsaleGenTest.js
- test/MarketMaker.js
- test/commands.js
- test/generators.js
- test/helpers.js
It's the first step in adding the Market Maker to the property-based test.
> Add property-based test command to send tokens to MarketMaker

- contracts/VestedPayment.sol
- test/VestedPayment.js
> Time to Timestamp rename

- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
- test/helpers.js
Transactions should throw when address == 0. Property-based test commands should handle the exceptions fine
Fixes #87
> Add zero address to accountGen, to force exceptions in txs in tests

- scripts/test.sh
Ensures that the cleanup runs even if the script is interrupted
Also makes the code more clear by removing and renaming some vars
> Cleanup using trap in script.sh

- contracts/LifCrowdsale.sol
- contracts/LifMarketMaker.sol
- test/Crowdsale.js
- test/LifToken.js
- test/MarketMaker.js
- test/VestedPayment.js
- test/commands.js
- test/helpers.js
Changing the use of blocks for timestamps on Market maker and its tests, also testing the market maker after being created by a successful crowdsale.
> WIP Using timestamps on MarketMaker

- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
Also adds example of funding crowdsale without finalize
> Add composed command to fund crowdsale over soft cap and finalize it

- contracts/LifMarketValidationMechanism.sol
They are the same value and basically the same concept
Fixes #186
> Remove PERCENTAGE_FACTOR and use PRICE_FACTOR instead

- contracts/LifCrowdsale.sol
- contracts/LifMarketValidationMechanism.sol
- contracts/LifToken.sol
> Add doxygen-style comments

- contracts/LifToken.sol
- contracts/test-helpers/Message.sol
- test/LifToken.js
> Add return value on new transfer methods in token.

- test/CrowdsaleGenTest.js
- test/commands.js
- test/helpers.js
> Check total supply and presale wei in property-based test

- contracts/LifToken.sol
This is the way to have protection from SafeMath as we are using SafeMath for uint256 as per BasicToken
> Use uint256 in *data methods in liftoken

- test/CrowdsaleGenTest.js
- test/commands.js
It will make it easier to add more variations of this command, like one to fund below the min cap and finalize crowdsale
> Refactor fund and finalize crowdsale commands: extract start and fund command

- test/commands.js
- test/generators.js
Should increase the chance of running claimEth commands in tests
Related to #169
> Add fundCrowdsaleBelowMinCap command

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
- test/helpers.js
> add foundersWallet variable on LifCrowdsale contract

- contracts/LifMarketValidationMechanism.sol
- test/CrowdsaleGenTest.js
- test/MarketValidationMechanism.js
- test/commands.js
- test/generators.js
Also adds Pause & Unpause events in MVM
Fixes #222
> Add pause & unpause MVM test commands

- test/LifToken.js
Adds a few example tests to check some validations
> Increase test coverage in LifToken

- contracts/LifCrowdsale.sol
- contracts/LifMarketValidationMechanism.sol
- contracts/LifToken.sol
- contracts/VestedPayment.sol
- package.json
- yarn.lock
> Bump solc to 0.4.15 & truffle to 3.4.11

- contracts/LifMarketValidationMechanism.sol
- test/CrowdsaleGenTest.js
> Add variable to track reimbursed ether in MVM

- contracts/LifCrowdsale.sol
- contracts/LifMarketValidationMechanism.sol
- contracts/LifToken.sol
- contracts/VestedPayment.sol
> Add public visibility specifiers

- contracts/LifMarketValidationMechanism.sol
> Add ClaimedEth event on MVM claimEth calls

- contracts/LifMarketValidationMechanism.sol
- test/CrowdsaleGenTest.js
- test/MarketValidationMechanism.js
- test/commands.js
- test/generators.js
Also renames test commands, generators and some vars related to this
Fixes #261
> Rename claimEth and ClaimedEth to use wei instead of eth

- contracts/LifToken.sol
- test/CrowdsaleGenTest.js
- test/LifToken.js
- test/VestedPayment.js
- test/commands.js
- test/helpers.js
> Add missing tests, increase coverage

- scripts/ci.sh
- test/CrowdsaleGenTest.js
- test/MarketValidationMechanism.js
- test/commands.js
- test/helpers.js
> Check eth balances in property-based test

- scripts/coverage.sh
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
We should aim at a high coverage even without the property-based tests
> Do not run property-based tests in Coverage

- contracts/LifToken.sol
- contracts/SmartToken.sol
Create the SmatToken contact from the functions used in LifToken and import it in the LifToken contract.
> Add SmartToken contract

- test/CrowdsaleGenTest.js
- test/commands.js
Uses BigNumber in setWeiPerUSDinTGE test command to overcome the 15 significant digits in number error.
Fixes #214
> Fix issue with BigNumber and 15 significant digits on setWeiPerUSDinTGE test command

- test/Crowdsale.js
Goal is to take it to 100% (or almost 100%!)
> Add tests and increase coverage in LifCrowdsale.sol

- test/commands.js
> Remove pending TODOs

- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/commands.js
Only when there is excess over the soft cap the MVM is created
> Fix test command: no MVM is created when funds are exactly the soft cap amount

- contracts/LifToken.sol
* Make LifToken burnable, remove copied code
* Use PausableToken instead of Pausable
> Use BurnableToken and PausableToken

- contracts/LifChannels.sol
- test/LifChannels.js
The LifChannels contract is an simple implementation of state channels for ERC20 tokens. This contract allows the token holders to mediate and decide about how much the final value of a transaction is going to be.
The channel is opened by a token holder that previously approved the transfer of tokens to the LifChannels contract, once the channel is opened the tokens are transfered to the contract and the mediation of the funds start.
While the channel is opened the two parties can exchange signatures proving the allowance and claim of the funds to be transfered, in this case the sender will share signatures where he allows the receiver to claim certain amount of tokens and the receiver will share signatures where he is willing to claim that amount.
With those signatures the receiver and …
> Add Lif Channels

- .solcover.js
- README.md
- package.json
Reverts windingtree/LifToken#320
> Revert "Version 0.1.0"

- contracts/LifToken.sol
- test/LifToken.js
Reverts windingtree/LifToken#315
> Revert "Remove ERC827 functionality and tests"
