windingtree/lif-token

- README.md
- package.json
Makes installation easier and uses explicit version numbers
> Install truffle and ethereumjs-testrpc as devDependencies

- test/Crowdsale.js
- test/DAO.js
- test/LifToken.js
- test/helpers.js
They convert from Lif units to fraction of Lif units. Same as `ethToWei`.  While working on the codebase I found it confusing to know when to use which of them.
Even though I'm just using LifWei to represent "fraction of a Lif", we should find a good name for it"
Maybe @kvakes has a name for it? I remember you mentioned something a while ago, but I'm not sure...
> Rename format/parseBalance methods to lif2LifWei form

- scripts/test.sh
Makes running tests faster (full compilation takes 20s vs incremental compilation 3s in my laptop)
> Compile contracts first to make use of incremental compilation

- .travis.yml
- contracts/LifCrowdsale.sol
- package.json
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/helpers.js
- yarn.lock
Adds a property based test which generates a crowdsale and a sequence of commands to run on that crowdsale. It runs the commands, checking some invariants/properties that must be true on every command that is run.
The interesting thing is that any sequence of commands can be generated, in ways that unit tests would not cover (because it's too expensive to write all the possible combinations so we only write a few specific combinations that we as developers think should cover most of the important/edge cases).
Example of a property:
> `submitBid` must throw an exception if the status of the crowdsale is not equal to 2 (which means that the crowdsale is started)
Fixes #25
> [WIP] Propery-based tests

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
Add function for the owner of the crowdsale to add tokens to addresses, this tokens are taken in count as private presale payments. The owner has a maximun amount of tokens that he can add, thats why I also added a maxPrivatePresaleTokens variable on the contract.
> Add private presale tokens on LifCrowdsale with test command

- test/CrowdsaleGenTest.js
Small fix to test the privatePresale with wei and not tokens.
> Make private presale buy using wei and not tokens on CrowdsaleGenTest

- test/CrowdsaleGenTest.js
Makes the test more robust by creating the crowdsale with any of the known
addresses instead of always with the first address
Fixes #88
> Improve gen test: allow any owner for the crowdsale

- contracts/LifMarketMaker.sol
- test/MarketMaker.js
Sending eth in the constructor is not possible when creating the
contract from another contract, but we need the LifCrowdsale to be able
to send the funds to the MarketMaker when it creates it. So now it will
create the MarketMaker, transfer the funds (calling the fund method) and
then transfer ownership to the foundation wallet
> Add fund metthod to MM, extracted from constructor

- contracts/LifMarketMaker.sol
- test/MarketMaker.js
This way it can be used as the actual amount that can be claimed at
this moment which will be helpful at the end of the market maker
where the claimable amount is just the balance of the MM (so it's
independent from the claimed amount)
> Modify getMaxClaimbleWeiAmount to substract claimed amount

- contracts/LifMarketMaker.sol
- test/MarketMaker.js
Also updates max claimable eth calculation that depends on the tokens circulation
Fixes #123
> Market maker: burn tokens on buy

- test/LifToken.js
- test/commands.js
- test/helpers.js
We were considering any exception in the shouldThrow usual block in the
gen tests commands. The idea is that shouldThrow means whether the
transaction should throw on the blockchain or not, and it's usually
with the invalid opcode error, not with any error. This change makes
it so we only accept invalid opcode exception as the expected thrown
exception. Other kinds of exceptions should make the test to fail
> Tests: Add isInvalidOpcodeEx and improve exception handling

- contracts/LifCrowdsale.sol
- test/Crowdsale.js
- test/CrowdsaleGenTest.js
- test/LifToken.js
- test/MarketMaker.js
- test/VestedPayment.js
- test/commands.js
- test/generators.js
- test/helpers.js
* Change LifCrowdsale contract to work only with timestamps.
* Change the prop based tests for LifCrowdsale to work with timestamps.
* Using same simulateCrowdsale function form helpers on all tests.
> Add timestamps on LifCrowdsale

- scripts/test.sh
testrpc is being killed in some travis runs, and it's probably
because of high memory usage. Let's output testrpc memory usage when
running in CI so we can better understand what's going on
> Output testrpc memory usage to logs in travis

- test/CrowdsaleGenTest.js
- test/LifToken.js
- test/commands.js
- test/helpers.js
We should use BigNumber everywhere, especially when dealing with lif/eth amounts. This goes towards that direction. Also makes some minor cleanups
> Expand usage of BigNumber in tests

- contracts/LifCrowdsale.sol
- test/commands.js
Tranfering ownership to foundation once the market maker is created and funded from the crowdsale.
> Tranfering ownership to foundation once the market maker is created

- contracts/LifCrowdsale.sol
- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
funds the crowdsale for the amount remaining until the min cap and finalizes it. This way there's more chance the tests will also run on a finalized and funded crowdsale. Next step is to add a similar command to fund it until the market maker minimum
> Add fund and finalize crowdsale composed command in property-based test

- test/CrowdsaleGenTest.js
- test/commands.js
Uses BigNumber to avoid the errors due to too many decimals with primitive numbers. Error was
```
BigNumber Error: plus() number type has more than 15 significant digits: 0.0000016499999999999999
```
> Fix test example on fund below cap command

- .travis.yml
Runs 40 tests instead of 20. Regroups the tests to keep it running in just to 'yarn test' commands while trying to not run out of memory in testrpc
> Run more property-based tests in travis

- test/generators.js
jsc.integer has to be used to have a lower and upper limit. Also in some tests there's no need to have any limit so here we remove those.
> Fix usage of jsc.nat and jsc.integer in tests

- test/CrowdsaleGenTest.js
- test/commands.js
Both commands don't need to check for address 0x0 as the from/sender
address. Only the transferFrom has to check for address 0x0 in the 
to address
Fixes #205
> Fix approve and transferFrom commands

- test/Crowdsale.js
- test/generators.js
It creates too many test that don't even get to create the crowdsale. Better to have a
test for that specific example and run the tests with commands with at least the
crowdsale created successfully
> Do not use zero address to create crowdsale in prop-based tests

- test/CrowdsaleGenTest.js
- test/commands.js
For example a sequence of fund below cap (without finalize) and a fund over cap was making the second one to fail this assert because there was some previous funding in the crowdsale already
> Fix fund over soft cap command with some funding before it runs

- test/CrowdsaleGenTest.js
When a failure is found in the property-based tests, it's useful to grab the failed example and construct a specific test for that example. This makes it easier by generating the code that makes the body of that example
```js
1) Contract: LifCrowdsale Property-based test should fund and finalize over cap and then send tokens to MVM fine:
Error: command {"type":"MVMSendTokens","tokens":4,"from":4} has thrown.
Error: Error: VM Exception while processing transaction: invalid opcode
at runGeneratedCrowdsaleAndCommands (test/CrowdsaleGenTest.js:156:19)
at process._tickCallback (internal/process/next_tick.js:109:7)
```
```js
1) Contract: LifCrowdsale Property-based test should fund and finalize over cap and then send tokens to MVM fine:
Error: command …
```
> Property-based tests: improve output to make it easier to reproduce failures

- truffle.js
Uses bail as example, which allows to stop test runs as soon as the first failure is found, useful during development
I'm not sure if this is the best way to do this. I didn't know about this option or even how to pass options to mocha. AFAIK the possible options are shown [here](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options) and explanations can be obtained running `./node_modules/.bin/mocha --help`
I don't think this should be put in the README, it's too specific to running the tests. It is in [truffle docs](http://truffleframework.com/docs/advanced/configuration#mocha) but I don't think it's very visible/easy to find.
What do you think @AugustoL? Feel 100% free to close it or merge it :)
> Add a commented out mocha option to show how to pass such options

- test/CrowdsaleGenTest.js
- test/commands.js
Shows that message when the exception is thrown when using the command not from CrowdsaleGenTest (in that case the message was being shown explicitly from the exception handler there, now it would show when used from anywhere)
> Add message to ExceptionRunningCommand

- test/CrowdsaleGenTest.js
- test/commands.js
It was expecting to throw when NOT funded, it's the other way around
Fixes #216
> Fix claimEth test command: should throw on funded crowdsale

- test/CrowdsaleGenTest.js
- test/MarketValidationMechanism.js
- test/commands.js
- test/generators.js
Adds a specific example that was failing, refactors the MVM tests by adding its commands as property-based test commands in `commands.js`
Fixes #156
> More MVM property-based tests

- test/CrowdsaleGenTest.js
This assertion usually fails when running the tests in travis with coverage instrumentation on. Maybe it affects the internal clock in testrpc somehow so there's a bit of drift in time calculations. Not sure but let's just disable this assertion in this environment
> Skip assertion about MVMMonth on solidity coverage

- test/CrowdsaleGenTest.js
- test/commands.js
Instead of using the comparison operators (>, <, etc), we have to use BigNumber's gt, lt, etc
> Fix MVMClaimEth command: use bignumber gt

- contracts/LifCrowdsale.sol
We can just use weiRaised instead. Then we can use this.balance to do
the actual transfer of funds, to include any remaining funds. But to
check against the cap, weiRaised is fine
Fixes #245
> Do not use this.balance in LifCrowdsale to check cap

- contracts/LifToken.sol
It's not very useful, and this way we save some gas
Thanks to CoinFabrik for reporting this issue in their audit
> Remove indexed from value param in Burn event

- contracts/LifCrowdsale.sol
Methods like validPurchase and hasEnded are converted to modifiers
funded is not converted to modifier because its bool return value is used in the logic of finalize
Fixes #251
> Convert some methods to modifiers

- test/commands.js
nextTimestamp taken from 'latest' block before running tx is not a robust way of getting the timestamp used during the creation of the MVM contract. We have to actually get the timestamp after the block was mined to get a consistent timestamp. This was causing random build failures that were quite hard to debug
Fixes #267
> Fix time drift in MVM timestamp in tests

- .travis.yml
- scripts/ci.sh
Allowing the coverage step to fail, makes the build to finish faster (at least the test part, which is the most important to have feedback from)
Fixes #178
> Run coverage in travis in parallel to the tests

- contracts/LifToken.sol
Comment taken from zeppelin's approve method in https://github.com/OpenZeppelin/zeppelin-solidity/pull/446
Fixes #246
> Add comment on double-spend attack vector in approveData

- contracts/LifToken.sol
- test/LifToken.js
Added the events in the *Data methods, and in burn
Fixes #248
> Add missing Transfer and Approval events

- contracts/LifMarketValidationMechanism.sol
- test/commands.js
NOTE: This issue was only affecting the amount that the foundation would be able to claim from the MVM after there were some reimbursements made to token holders (via `sendTokens` transactions). We think the impact was not really high because it only delays the amount that the foundation could claim for the burned tokens (only for those tokens) depending on when the `sendTokens` tx is made:
- If the `sendTokens` tx is made early on the MVM lifetime, the amount that the foundation could claim from those tokens is super low, because of the distribution curve that follows an exponential distribution where the distribution amounts are low at the beginning and high approaching the end of the lifetime).
- If the `sendTokens` tx is made later, then even though the amount that the foundation …
> MVM: Avoid delayed claim issue by adding claimable from reimbursed

- package.json
- test/commands.js
- yarn.lock
Fixes #265 
To make it sure there's no impact from changes in zeppelin-solidity base classes, I checked the diff from the classes that we use using the following command (in the zeppelin-solidity codebase):
git diff v1.2.0..v1.3.0 contracts/token/ERC20.sol contracts/token/ERC20Basic.sol contracts/token/BasicToken.sol contracts/token/StandardToken.sol contracts/token/MintableToken.sol contracts/ownership/Ownable.sol contracts/math contracts/lifecycle/Migrations.sol contracts/lifecycle/Pausable.sol
(it would be nice if another pair of eyes also take a look)
> Zeppelin-solidity 1.3.0

- test/commands.js
LifCrowdsale `finalize` is a quite expensive transaction because it creates a few contracts (MVM and VestedPayments). Let's assert that it uses less gas than the limit in mainnet
Fixes #247
> Assert on finalize that gasUsed should be less than limit

- test/CrowdsaleGenTest.js
Funds the crowdsale below min cap and finalizes it, so the claimEth
can run successfully, returning the eth to the holder account
> Add specific example with claimEth

- test/CrowdsaleGenTest.js
- test/commands.js
Depending on the full test sequence, a fund below soft cap and finalize command can end creating a 48 months MVM, depending on the preceding sendTransation/buyTokens commands. This PR adds a test to verify this, and the fix in the `runFundCrowdsaleBelowSoftCap` test command
> Fix test command: Fund below soft cap can end creating a 48 months MVM

- contracts/LifToken.sol
- test/LifToken.js
Calls super.approve, super.transfer & super.transferFrom from the corresponding
*Data methods (approveData, transferData & transferDataFrom)
> Refactor *Data methods in LifToken to use super methods

- README.md
It's the fix suggested in https://github.com/lemurheavy/coveralls-public/issues/116#issuecomment-333808216 to overcome the github aggresive caching that doesn't play well with coverage badge (it stays too long at the same value)
> README coverage badge: add a request param to invalidate cache

- contracts/LifCrowdsale.sol
- test/commands.js
buyTokens, claimEth and finalize should not be allowed while paused
> LifCrowdsale: Disallow some methods when paused

- contracts/LifCrowdsale.sol
- test/CrowdsaleGenTest.js
- test/commands.js
- test/generators.js
- test/helpers.js
We need to add a function to return the purchase of tokens from contributors in the crowdsale to reject contributions from unverified users. The return of purchases will be executed after the crowdsale ends and before the finalization of the crowdsale.
This changes add that function and change the tests to test it correctly.
> Add return purchase function in crowdsale

- .npmignore
- .travis.yml
- index.js
- package.json
- yarn.lock
- This setup will publish every tagged commit in `master` branch to npmjs.org into @windingtree/lif-token
- The resulting package contains only compiled JSON files and an `index.js`
- This expects that travis has the NPM_TOKEN environment variable set up in Travis CI. This token should be tied to `chadima.jiri@gmail.com` npmjs account OR another account, but then we have to change the email field in `.travis.yml`. I was not able to get encrypted API keys working.
- I have also scoped the package under `windingtree` organization in npmjs
> Allows publishing to NPM automatically from travis

- .travis.yml
This will prevent publishing to npm from forks. The previous setup was actually wrong.
> chore: Pins travis CI auto releases to windingtree repo

- .gitignore
- package-lock.json
This unifies `.gitignore` with `wt-contracts` and enables `npm version` command which does not work without `package-lock` in the repository.
> chore: Puts package-lock file into git

- .npmignore
- package.json
This is a temporary solution until #319 is resolved. It will allow us to simplify dependency management in wt-contracts for now.
> chore: Puts sol source contracts into artifact published on npmjs

- .gitattributes
As per https://medium.com/@robertodev/solidity-and-github-42a3ca375618
> chore: Forces github to highlight solidity source code
